# Multicast is used to efficiently
# identify hosts on the network
mcast_group: "224.1.1.1"
mcast_port: 5000

# A TCP server runs to field information requests
server_port: 6753
server_host: "0.0.0.0"
# (server_hostname defaults to $HOSTNAME)
# server_hostname: "jspisak-labmachine"

database_cache: test_cache.yaml

# Delay startup to make sure interfaces are up before broadcasting
startup_delay: 1.

# Each interface that uses multicast
# must be explicitly configured
broadcast_on_start: true
broadcast_on_interval: 1.
interfaces_blacklist: [ docker*, br-*, lo ]
# interfaces_whitelist:
#     eno1:
#         # Whether or not to send a broadcast on startup
#         broadcast_on_start: true
#         # Whether or not to broadcast on a set interval
#         broadcast_on_interval: 1.

host_files:
-   file_path: /etc/hosts
    update_period: 1.