#!/usr/bin/env python3
import subprocess
import shutil
import shlex
import os

if __name__ == "__main__":
    print("Running host info tools installer!")
    config_file_dest = "/etc/host_info_tools/host_info_server.yaml"
    service_file_dest = "/etc/systemd/system/host_info_server.service"

    tmp_install_dir = os.path.dirname(os.path.realpath(__file__))
    config_file = os.path.join(tmp_install_dir, "config/host_info_server.yaml")
    service_file = os.path.join(tmp_install_dir, "config/host_info_server.service")

    try:
        os.mkdir("/etc/host_info_tools")
    except:
        pass
    shutil.copy("/usr/local/host_info_tools/host_info_server.yaml", "/etc/host_info_tools/host_info_server.yaml")
    os.symlink("/usr/local/host_info_tools/host_info_server.service", "/etc/systemd/system/host_info_server.service")

    subprocess.check_output(shlex.split("systemctl enable host_info_server"))
    subprocess.check_output(shlex.split("systemctl start host_info_server"))

    