#!/usr/bin/env python3
import json
import socket
import sys
import os

from host_info_tools import message_interface as hit_mi
from host_info_tools import host_database as hit_hd

if __name__ == "__main__":
    local_info = hit_hd.LocalHostInfo("jspisak-labmachine")
    database = hit_hd.HostDatabase(local_info)
    hit_mi.Server("0.0.0.0", 6753, database)